- id: doi:10.1101/2024.07.09.599086
  type: paper
  description: The Open Pediatric Cancer Project
  date: 2024-
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11257555/figure/F1/
  buttons:
    - type: source
      text: Manuscript Source
      link: https://github.com/rokitalab/OpenPedCan-manuscript
    - type: manubot
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
    - pediatric cancer
    - genomics
  repo: rokitalab/OpenPedCan-manuscript

- id: doi:10.1101/2024.08.03.606419
  type: paper
  description: Characterization of aberrant splicing in pediatric central nervous system tumors reveals CLK1 as a candidate oncogenic dependency
  date: 2022-08-22
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11326178/figure/F1/
  tags:
    - pediatric cancer
    - splicing
  repo: rokitalab/clk1-splicing

- id: doi:10.1093/bioinformatics/btae114
  type: paper
  description: AutoGVP
  date: 2024-02-29
  tags:
  - open science
  - germline
  - cancer
  image: https://academic.oup.com/view-large/figure/445059631/btae114f1.tif
  buttons:
    - type: tool
      link: https://github.com/diskin-lab-chop/AutoGVP
  repo: diskin-lab-chop/AutoGVP